name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: jsdaniell/create-json@v1.2.2
        with:
          name: "serviceAccountKey.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          dir: 'api/src/main/resources/'

      - uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: 'api/src/main/resources/keyBytes.txt'
          FILE_DATA: ${{ secrets.ENCRYPTION_KEY }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: cd api && chmod +x gradlew && ./gradlew bootJar
      
      - name: Copy bin to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: api/build/libs/api-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/
      
      - name: Restart server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ec2-user/api/build/libs/
            ls
            killall java
            nohup java -jar api-0.0.1-SNAPSHOT.jar > log.txt &
            cat log.txt
            iptables -A INPUT -i eth0 -p tcp --dport 80 -j ACCEPT
            iptables -A INPUT -i eth0 -p tcp --dport 8080 -j ACCEPT
            iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
